// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxzbartwbukfbqtylvtk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4emJhcnR3YnVrZmJxdHlsdnRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5OTY0MzEsImV4cCI6MjA2MjU3MjQzMX0.FBwOUvJHQ7o25jrpPdXq9qtR0W_FGmvXwF6fwbQMHrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);